In [3]:
import pandas as pd
import pyodbc 
import sqlalchemy as sa
engine = sa.create_engine('mssql+pyodbc://WRJMDLVPW04/ITDPopSynIII?driver=ODBC Driver 17 for SQL Server')

tables = sa.inspect(engine).get_table_names()
tables

['control_totals_county',
 'control_totals_state',
 'control_totals_taz',
 'csv_filenames',
 'hh_subset',
 'hhIds',
 'hhtable',
 'households',
 'incidence',
 'occupation',
 'persons',
 'perstable',
 'psam_h11',
 'psam_p11',
 'synpop_hh',
 'synpop_person',
 'temphh',
 'temppers']

In [4]:
control_taz = pd.read_sql_table('control_totals_taz', engine)
control_taz

,STATEFPS,COUNTYFPS,CNTYIDFP00,ZONEID,TOTPOP,TOTHH,HHSIZE1,HHSIZE2,HHSIZE3,HHSIZE4,...,HHWORK3,CATINC1,CATINC2,CATINC3,PUMACE00,COUNTYGEOID,ZONEGEOID,PUMA,MAZ,TAZ
0,16,1,16001,123,343.0,164.0,136.0,20.0,2.0,5.0,...,1.0,9.0,21.0,44.0,None,16001,160010123,1600300,1,1
1,16,1,16001,124,18.0,12.0,5.0,5.0,0.0,2.0,...,0.0,11.0,11.0,10.0,None,16001,160010124,1600300,2,1
2,16,1,16001,125,358.0,214.0,125.0,62.0,22.0,4.0,...,1.0,63.0,56.0,44.0,None,16001,160010125,1600300,3,1
3,16,1,16001,126,413.0,256.0,179.0,48.0,13.0,12.0,...,1.0,56.0,49.0,39.0,None,16001,160010126,1600300,4,1
4,16,1,16001,127,170.0,81.0,28.0,33.0,11.0,7.0,...,1.0,42.0,36.0,29.0,None,16001,160010127,1600300,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2768,53,63,53063,2751,813.0,813.0,105.0,324.0,159.0,116.0,...,72.0,110.0,212.0,616.0,None,53063,530632751,5310400,2769,63
2769,53,63,53063,2752,870.0,870.0,148.0,362.0,92.0,154.0,...,63.0,134.0,200.0,503.0,None,53063,530632752,5310400,2770,63
2770,53,75,53075,2766,47973.0,18650.0,6519.0,6514.0,2494.0,1752.0,...,0.0,6.0,4.0,3.0,None,53075,530752766,5310600,2771,64
2771,56,23,56023,2826,19581.0,7545.0,1814.0,2988.0,954.0,819.0,...,0.0,0.0,0.0,0.0,None,56023,560232826,5600100,2772,65
2772,56,39,56039,2827,23331.0,9609.0,2613.0,3619.0,1439.0,1262.0,...,2.0,5.0,9.0,42.0,None,56039,560392827,5600100,2773,66

In [6]:
control_taz_co = control_taz.groupby('CNTYIDFP00').agg(TOTPOP = ('TOTPOP', sum), TOTHH = ('TOTHH', sum))
control_taz_co

C:\Users\andrew.rohne\AppData\Local\Temp\3\ipykernel_7452\2976969432.py:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  control_taz_co = control_taz.groupby('CNTYIDFP00').agg(TOTPOP = ('TOTPOP', sum), TOTHH = ('TOTHH', sum))

              TOTPOP     TOTHH
CNTYIDFP00
16001       535193.0  163685.0
16003         4379.0    1927.0
16005        88054.0   32394.0
16007         6374.0    2427.0
16009         9531.0    3875.0
...              ...       ...
53051        13401.0    5621.0
53063       215648.0  207772.0
53075        47973.0   18650.0
56023        19581.0    7545.0
56039        23331.0    9609.0

[66 rows x 2 columns]

In [15]:
control_co = pd.read_sql_table('control_totals_county', engine)
control_co.loc[control_co['CNTYIDFP00'] == 16001].transpose()

                     0
STATEFPS          16.0
COUNTYGEOID    16001.0
CNTYIDFP00     16001.0
PUMA         1600300.0
POP           535193.0
AGE1           35834.0
AGE2           48583.0
AGE3           22622.0
AGE4           13319.0
AGE5           46478.0
AGE6           76027.0
AGE7           71412.0
AGE8           64294.0
AGE9           60838.0
AGE10          48408.0
AGE11          20681.0
AGE12           7861.0
OCCP1         128256.0
OCCP2           9439.0
OCCP3          45000.0
OCCP4          71857.0
OCCP5          29434.0
OCCP6          35262.0
OCCP7            536.0
OCCP8         192780.0
OCCP9            748.0
TAZ                1.0

In [16]:
control_co.loc[control_co['CNTYIDFP00'] == 16001][['AGE1', 'AGE2', 'AGE3', 'AGE4', 'AGE5', 'AGE6', 'AGE7', 'AGE8', 'AGE9', 'AGE10', 'AGE11', 'AGE12']]

,AGE1,AGE2,AGE3,AGE4,AGE5,AGE6,AGE7,AGE8,AGE9,AGE10,AGE11,AGE12
0,35834.0,48583.0,22622.0,13319.0,46478.0,76027.0,71412.0,64294.0,60838.0,48408.0,20681.0,7861.0

In [ ]:

# engine

table = 'synpop_hh'
conn = 'mssql+pyodbc://WRJMDLVPW04/ITDPopSynIII?driver=ODBC Driver 17 for SQL Server'

synpop_hh = pd.read_sql_table(table, conn)
synpop_hh