In [95]:
import pandas as pd
import os

OLD_MODEL_INPUT = r'C:\projects\IdahoSTDM\ITD_STDM\IdahoSTDM\ITDSTDM\inputs'
OLD_MODEL_PATH = r'C:\projects\IdahoSTDM\ITD_STDM\IdahoSTDM\ITDSTDM\outputs_2010'
NEW_MODEL_INPUT = r'C:\projects\IdahoSTDM\ITD_STDM\IdahoSTDM\ITDSTDM\inputs2020'
NEW_MODEL_PATH = r'C:\projects\IdahoSTDM\ITD_STDM\IdahoSTDM\ITDSTDM\outputs2020_newTAZ'

old_taz = pd.read_csv(os.path.join(OLD_MODEL_INPUT, 'tazs.csv'))
new_taz = pd.read_csv(os.path.join(NEW_MODEL_INPUT, 'tazs.csv'))

old_pop = pd.read_csv(os.path.join(OLD_MODEL_PATH, 'PopSyn0_Per.csv')).merge(old_taz[['STDM_TAZ', 'State', 'County']], how = 'left', on = 'STDM_TAZ')
old_hh = pd.read_csv(os.path.join(OLD_MODEL_PATH, 'PopSyn0_HH.csv')).merge(old_taz[['STDM_TAZ', 'State', 'County']], how = 'left', on = 'STDM_TAZ')

new_pop = pd.read_csv(os.path.join(NEW_MODEL_PATH, 'PopSyn0_Per.csv')).merge(new_taz[['STDM_TAZ', 'State', 'County']], how = 'left', on = 'STDM_TAZ')
new_hh = pd.read_csv(os.path.join(NEW_MODEL_PATH, 'PopSyn0_HH.csv')).merge(new_taz[['STDM_TAZ', 'State', 'County']], how = 'left', on = 'STDM_TAZ')

# Individual Person Comparison

For Bear Lake, since it's small.

In [115]:
# new_pop = new_pop[new_pop['County'] == 'Bear Lake']
# old_pop = old_pop[old_pop['County'] == 'Bear Lake']

def join_persons(attribute):
    return(old_pop.groupby(attribute).agg(old = (attribute, 'count')).join(new_pop.groupby(attribute).agg(new = (attribute, 'count'))).join(old_pop.groupby(attribute).agg(old_pct = (attribute, 'count')) / old_pop.shape[0]).join(new_pop.groupby(attribute).agg(new_pct = (attribute, 'count')) / new_pop.shape[0]).style.format({'old': '{:,.0f}', 'new': '{:,.0f}', 'old_pct': '{:.1%}', 'new_pct': '{:.1%}'}))

join_persons('SEX')

In [116]:
join_persons('SCHOOL')

In [117]:
join_persons('RLABOR')

In [118]:
join_persons('INDUSTRY')

In [119]:
join_persons('OCCUP')

In [120]:
join_persons('SW_UNSPLIT_IND')

In [121]:
join_persons('SW_OCCUP')

In [122]:
join_persons('SW_SPLIT_IND')

In [123]:
join_persons('WORK_OCC')

# Household Comparison

In [124]:
old_hh = old_hh #[old_hh['County'] == 'Bear Lake']
new_hh = new_hh #[new_hh['County'] == 'Bear Lake']

def join_hh(attribute):
    return(old_hh.groupby(attribute).agg(old = (attribute, 'count')).join(new_hh.groupby(attribute).agg(new = (attribute, 'count'))).join(old_hh.groupby(attribute).agg(old_pct = (attribute, 'count')) / old_hh.shape[0]).join(new_hh.groupby(attribute).agg(new_pct = (attribute, 'count')) / new_hh.shape[0]).style.format({'old': '{:,.0f}', 'new': '{:,.0f}', 'old_pct': '{:.1%}', 'new_pct': '{:.1%}'}))

join_hh('PERSONS')

In [125]:
join_hh('UNITS1')

In [126]:
join_hh('AUTOS')

In [127]:
inc_bins = [0, 10000, 25000, 50000, 75000, 100000, 150000, 200000, 250000, 9999999]
inc_labels = ['< $10k', '$10k - $25k', '$25k - $50k', '$50k - $75k', '$75k - $100k', '$100k - $150k', '$150k - $200k', '$200k - $250k', '$250k +']

old_hh['INC_GROUP'] = pd.cut(old_hh['RHHINC'], bins = inc_bins, labels = inc_labels)
new_hh['INC_GROUP'] = pd.cut(new_hh['RHHINC'], bins = inc_bins, labels = inc_labels)

join_hh('INC_GROUP')

C:\Users\andrew.rohne\AppData\Local\Temp\4\ipykernel_4060\513420895.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  return(old_hh.groupby(attribute).agg(old = (attribute, 'count')).join(new_hh.groupby(attribute).agg(new = (attribute, 'count'))).join(old_hh.groupby(attribute).agg(old_pct = (attribute, 'count')) / old_hh.shape[0]).join(new_hh.groupby(attribute).agg(new_pct = (attribute, 'count')) / new_hh.shape[0]).style.format({'old': '{:,.0f}', 'new': '{:,.0f}', 'old_pct': '{:.1%}', 'new_pct': '{:.1%}'}))
C:\Users\andrew.rohne\AppData\Local\Temp\4\ipykernel_4060\513420895.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  return(old_hh.groupby(attribute).agg(old = (attribute, 'count')).join(new_hh.groupby(attribute).agg(new = (attribute, 'count'))).join(old_hh.groupby(attribute).agg(old_pct = (attribute, 'count')) / old_hh.shape[0]).join(new_hh.groupby(attribute).agg(new_pct = (attribute, 'count')) / new_hh.shape[0]).style.format({'old': '{:,.0f}', 'new': '{:,.0f}', 'old_pct': '{:.1%}', 'new_pct': '{:.1%}'}))
C:\Users\andrew.rohne\AppData\Local\Temp\4\ipykernel_4060\513420895.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  return(old_hh.groupby(attribute).agg(old = (attribute, 'count')).join(new_hh.groupby(attribute).agg(new = (attribute, 'count'))).join(old_hh.groupby(attribute).agg(old_pct = (attribute, 'count')) / old_hh.shape[0]).join(new_hh.groupby(attribute).agg(new_pct = (attribute, 'count')) / new_hh.shape[0]).style.format({'old': '{:,.0f}', 'new': '{:,.0f}', 'old_pct': '{:.1%}', 'new_pct': '{:.1%}'}))
C:\Users\andrew.rohne\AppData\Local\Temp\4\ipykernel_4060\513420895.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  return(old_hh.groupby(attribute).agg(old = (attribute, 'count')).join(new_hh.groupby(attribute).agg(new = (attribute, 'count'))).join(old_hh.groupby(attribute).agg(old_pct = (attribute, 'count')) / old_hh.shape[0]).join(new_hh.groupby(attribute).agg(new_pct = (attribute, 'count')) / new_hh.shape[0]).style.format({'old': '{:,.0f}', 'new': '{:,.0f}', 'old_pct': '{:.1%}', 'new_pct': '{:.1%}'}))

In [128]:
inc_bins = [0, 37408, 74814, 9999999]
inc_labels = ['Low', 'Med', 'High']

old_hh['INC_GROUP2'] = pd.cut(old_hh['RHHINC'], bins = inc_bins, labels = inc_labels)
new_hh['INC_GROUP2'] = pd.cut(new_hh['RHHINC'], bins = inc_bins, labels = inc_labels)

join_hh('INC_GROUP2')

C:\Users\andrew.rohne\AppData\Local\Temp\4\ipykernel_4060\513420895.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  return(old_hh.groupby(attribute).agg(old = (attribute, 'count')).join(new_hh.groupby(attribute).agg(new = (attribute, 'count'))).join(old_hh.groupby(attribute).agg(old_pct = (attribute, 'count')) / old_hh.shape[0]).join(new_hh.groupby(attribute).agg(new_pct = (attribute, 'count')) / new_hh.shape[0]).style.format({'old': '{:,.0f}', 'new': '{:,.0f}', 'old_pct': '{:.1%}', 'new_pct': '{:.1%}'}))
C:\Users\andrew.rohne\AppData\Local\Temp\4\ipykernel_4060\513420895.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  return(old_hh.groupby(attribute).agg(old = (attribute, 'count')).join(new_hh.groupby(attribute).agg(new = (attribute, 'count'))).join(old_hh.groupby(attribute).agg(old_pct = (attribute, 'count')) / old_hh.shape[0]).join(new_hh.groupby(attribute).agg(new_pct = (attribute, 'count')) / new_hh.shape[0]).style.format({'old': '{:,.0f}', 'new': '{:,.0f}', 'old_pct': '{:.1%}', 'new_pct': '{:.1%}'}))
C:\Users\andrew.rohne\AppData\Local\Temp\4\ipykernel_4060\513420895.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  return(old_hh.groupby(attribute).agg(old = (attribute, 'count')).join(new_hh.groupby(attribute).agg(new = (attribute, 'count'))).join(old_hh.groupby(attribute).agg(old_pct = (attribute, 'count')) / old_hh.shape[0]).join(new_hh.groupby(attribute).agg(new_pct = (attribute, 'count')) / new_hh.shape[0]).style.format({'old': '{:,.0f}', 'new': '{:,.0f}', 'old_pct': '{:.1%}', 'new_pct': '{:.1%}'}))
C:\Users\andrew.rohne\AppData\Local\Temp\4\ipykernel_4060\513420895.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  return(old_hh.groupby(attribute).agg(old = (attribute, 'count')).join(new_hh.groupby(attribute).agg(new = (attribute, 'count'))).join(old_hh.groupby(attribute).agg(old_pct = (attribute, 'count')) / old_hh.shape[0]).join(new_hh.groupby(attribute).agg(new_pct = (attribute, 'count')) / new_hh.shape[0]).style.format({'old': '{:,.0f}', 'new': '{:,.0f}', 'old_pct': '{:.1%}', 'new_pct': '{:.1%}'}))

In [158]:
pums_hh = pd.read_csv(os.path.join(NEW_MODEL_INPUT, 'PopSyn', 'ss11hid.csv'))
pums_hh['_adjusted_income'] = (pums_hh['HINCP'] * (pums_hh['ADJINC'] / 1000000))/(258.8/172.2)
pums_hh['_adjinc_group'] = pd.cut(pums_hh['_adjusted_income'], bins = inc_bins, labels = inc_labels)
pums_hh.groupby('_adjinc_group').agg(mean_inc = ('_adjusted_income', 'mean'), n = ('_adjinc_group', 'count'))

C:\Users\andrew.rohne\AppData\Local\Temp\4\ipykernel_4060\1084031065.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  pums_hh = pd.read_csv(os.path.join(NEW_MODEL_INPUT, 'PopSyn', 'ss11hid.csv'))
C:\Users\andrew.rohne\AppData\Local\Temp\4\ipykernel_4060\1084031065.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  pums_hh.groupby('_adjinc_group').agg(mean_inc = ('_adjusted_income', 'mean'), n = ('_adjinc_group', 'count'))

                    mean_inc      n
_adjinc_group
Low             20305.913803  35529
Med             53361.844719  24627
High           128022.059526  14565

In [159]:
old_pums_hh = pd.read_csv(os.path.join(OLD_MODEL_INPUT, 'PopSyn', 'ss11hid.csv'))

inc_adj = {
    1102938: 1.016787*1.05156,
    1063801: 1.018389*1.01265,
    1048026: 0.999480*1.01651,
    1039407: 1.007624*1.00000,
    1018237: 1.018237*0.96942
}

old_pums_hh['_adjusted_income'] = pd.to_numeric(old_pums_hh['HINCP'] , errors='coerce').fillna(0) * old_pums_hh['ADJINC'].map(inc_adj) / 1.266113 #old_pums_hh['HINCP'] * old_pums_hh['ADJINC'].map(inc_adj) / 1.266113
old_pums_hh['_adjinc_group'] = pd.cut(old_pums_hh['_adjusted_income'], bins = inc_bins, labels = inc_labels)
old_pums_hh.groupby('_adjinc_group').agg(mean_inc = ('_adjusted_income', 'mean'), n = ('_adjinc_group', 'count'))

C:\Users\andrew.rohne\AppData\Local\Temp\4\ipykernel_4060\126918195.py:1: DtypeWarning: Columns (94) have mixed types. Specify dtype option on import or set low_memory=False.
  old_pums_hh = pd.read_csv(os.path.join(OLD_MODEL_INPUT, 'PopSyn', 'ss11hid.csv'))
C:\Users\andrew.rohne\AppData\Local\Temp\4\ipykernel_4060\126918195.py:13: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  old_pums_hh.groupby('_adjinc_group').agg(mean_inc = ('_adjusted_income', 'mean'), n = ('_adjinc_group', 'count'))

                    mean_inc      n
_adjinc_group
Low             20042.203699  31632
Med             53168.310192  20905
High           118733.263215   9893

In [162]:
pums_hh.groupby('_adjinc_group').agg(new_mean_inc = ('_adjusted_income', 'mean'), new_n = ('_adjinc_group', 'count')).join(
    old_pums_hh.groupby('_adjinc_group').agg(old_mean_inc = ('_adjusted_income', 'mean'), old_n = ('_adjinc_group', 'count'))
).style.format('{:,.0f}')

C:\Users\andrew.rohne\AppData\Local\Temp\4\ipykernel_4060\4021139647.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  pums_hh.groupby('_adjinc_group').agg(new_mean_inc = ('_adjusted_income', 'mean'), new_n = ('_adjinc_group', 'count')).join(
C:\Users\andrew.rohne\AppData\Local\Temp\4\ipykernel_4060\4021139647.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  old_pums_hh.groupby('_adjinc_group').agg(old_mean_inc = ('_adjusted_income', 'mean'), old_n = ('_adjinc_group', 'count'))